# Generated by Django 3.2.19 on 2023-07-13 13:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='не более 100 символов', max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes_discussion', models.ManyToManyField(blank=True, related_name='discussion_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувшие')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_ok_discussion', to='discussions.discussion')),
                ('saves_discussion', models.ManyToManyField(blank=True, related_name='blog_discussion_save', to=settings.AUTH_USER_MODEL, verbose_name='Сохранившие')),
            ],
            options={
                'verbose_name': 'Дискусия',
                'verbose_name_plural': 'Дискусии',
            },
        ),
    ]
